{
 "title": "Autrik Dashboard",
 "time": { "from": "2025-05-11T13:31:39.559Z", "to": "2025-05-11T13:42:05.259Z" },
 "panels": [
  {
   "title": "Flight Summary",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT startTime, flight_id, startCoordinate_latitude, startCoordinate_longitude FROM \"autrik\".\"flight_summary\" WHERE ( flight_id = 'DJIFlightRecord_2025-05-11_[15-31-39]_results' )"
    },
    {
     "rawSql": "SELECT flightControllerState_aircraftLocation_latitude, flightControllerState_aircraftLocation_longitude FROM \"autrik\".\"flight_info\" WHERE ( flight_id = 'DJIFlightRecord_2025-05-11_[15-31-39]_results' ) ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT aircraftName, platform, totalTime, maxHorizontalSpeed, maxVirticalSpeed, maxHeight FROM \"autrik\".\"flight_summary\" WHERE ( flight_id = 'DJIFlightRecord_2025-05-11_[15-31-39]_results' )"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT flightControllerState_isFailsafeEnabled, batteryState_chargeRemainingInPercent, cameraState_remainingSpaceInMB, cameraState_availableCaptureCount, flightControllerState_countOfFlights, flightControllerState_cumulativeFlightDistance FROM \"autrik\".\"flight_info\" WHERE ( flight_id = 'DJIFlightRecord_2025-05-11_[15-31-39]_results' ) ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Pitch, roll and yaw",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as \"time\", flightControllerState_attitude_pitch, flightControllerState_attitude_roll, flightControllerState_attitude_yaw FROM \"autrik\".\"flight_info\" WHERE ( flight_id = 'DJIFlightRecord_2025-05-11_[15-31-39]_results' ) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Flight Path",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as \"time\", flightControllerState_aircraftLocation_latitude, flightControllerState_aircraftLocation_longitude FROM \"autrik\".\"flight_info\" WHERE ( flight_id = 'DJIFlightRecord_2025-05-11_[15-31-39]_results' ) AND ( flightControllerState_aircraftLocation_latitude <= 70 ) AND ( flightControllerState_aircraftLocation_latitude >= 40 ) AND ( flightControllerState_aircraftLocation_longitude <= 12 ) AND ( flightControllerState_aircraftLocation_longitude >= 8 )"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as \"time\", flightControllerState_altitude FROM \"autrik\".\"flight_info\" WHERE ( flight_id = 'DJIFlightRecord_2025-05-11_[15-31-39]_results' ) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Battery %age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as \"time\", batteryState_chargeRemainingInPercent FROM \"autrik\".\"flight_info\" WHERE ( flight_id = 'DJIFlightRecord_2025-05-11_[15-31-39]_results' ) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as \"time\", batteryState_temperature FROM \"autrik\".\"flight_info\" WHERE ( flight_id = 'DJIFlightRecord_2025-05-11_[15-31-39]_results' ) ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Velocity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp as \"time\", flightControllerState_velocity_velocityX, flightControllerState_velocity_velocityY, flightControllerState_velocity_velocityZ FROM \"autrik\".\"flight_info\" WHERE ( flight_id = 'DJIFlightRecord_2025-05-11_[15-31-39]_results' ) ORDER BY time ASC"
    }
   ]
  }
 ]
}